apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-deployment
  labels:
    app: fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-app
          image: leeh1012/fastapi-app-app:ea5dbcdbf3f830bf8095798a1d72521bd3e6c729
          ports:
            - containerPort: 8000
